# -*- coding: utf-8 -*-
"""TimeSeries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wqg1DqrvARQc_tI_ENgy6xT9c0WZmHLt
"""

import streamlit as st
import pandas as pd
import numpy as np

DATA_URL = ('https://docs.google.com/spreadsheets/d/13OLznCJb5UwDnpgJxqzlejeVRiLaUxRRQeQLx9Lv-J8/edit?usp=share_link')
column_names=["Unique","Price",'Date',"Postcode",'Property_Type','Old_New','Duration','PAON','SAON','Street','Locality','Town_City','District','County','PPD','RecordStatus']

@st.cache_data(ttl=600)
def load_data(sheets_url):
    csv_url = sheets_url.replace("/edit#gid=", "/export?format=csv&gid=")
    return pd.read_csv(csv_url)

df = load_data(st.secrets[DATA_URL])

# Create a text element and let the reader know the data is loading.
data_load_state = st.text('Loading data...')
# Notify the reader that the data was successfully loaded.
data_load_state.text("Done! (using st.cache_data)")

st.subheader('Raw data')
#st.dataframe(data)



